### ISSUE TITLE
allow customized "MAX_HEIGHT" on Chromium based browsers

### ISSUE THREAD

**Issue by Andy2244** [foray1010/Popup-my-Bookmarks#32]
Hi,

it would be nice to have a "MAX_HEIGHT" UI setting for chromium based browsers, since some of them don't have the 596 limit. As example Vivaldi has no limits so we can finally get a large popup similar to what Firefox has. I juts tested the 5.0 version and works fine in Vivaldi 1.5 beta, with a 1000 height setting for me.

thx
Andy

PS: Btw would it be possible to change the popup location to the left side of the screen similar to a sidebar and use the firefox folder popup logic, expanding right multiple times? This might be possible in vivaldi, since its not as restrictive as chrome.

**Comment by foray1010** [comment]
```
As example Vivaldi has no limits so we can finally get a large popup similar to what Firefox has
```
Amazing!!! It actually give me real reason to officially support Chromium based  browsers
But consider the browser coverage (0.02% market share), I am not sure if Vivaldi worth us to put effort on
(source: https://www.sitepoint.com/browser-trends-august-2016-how-do-chromes-rivals-stack-up/)
Consider we have 18549 users and Chrome's market share is 57.99%, around 18549/0.5799*0.0002 = 7 users use Vivaldi, which is a really small number
But we can also assume that people installs extension tend to try other chrome browser like Vivaldi, but still, even there are 100 users, it is still very small number

Can you verify if Opera supports more than 600px, since it has higher market share (1.68%), it worth us to officially support it

**Comment by Andy2244** [comment]
I see the problem, i still can't fully use Vivaldi because the sync feature is still in development. I also assume that its a slow uphill battle even after Vivaldi gets sync and a mail client. 

Opera 41 unfortunately has the same restriction, maybe there is a possibility to ask the developers to relax this restriction as well, since they already modify the ui quite a bit.

Maybe there is a very easy and maintenance free check/change just for Vivaldi and this one setting for now?

**Comment by foray1010** [comment]
Since most of the user and I are not benefited by this feature, I am not going to put my time on it
But any PR is welcomed, just make sure that Chrome users cannot see this option, don't want to confuse them :)

**Comment by Andy2244** [comment]
I understand, i can fork the project and do my own changes. I still have no clue how to sign the extension so chrome stops complaining, but if i fully switch to Vivaldi i will figure this out.

thx
Andy

**Comment by foray1010** [comment]
you can never stop chrome complaining, only work around is use dev channel version of Chrome (not sure if Vivaldi disabled it by default)
