### ISSUE TITLE
Open context menu with options key

### ISSUE THREAD

**Issue by MartinLichtblau** [foray1010/Popup-my-Bookmarks#6]
It is possible to navigate through the bookmarks with the arrow keys, which I really like, but it's somehow not possible to open the context menu. 

Of course with the rightclick of the mouse it open but normally it sohuld also open when clicking the options key on the keyboard. I think this doesn't work because the cursor somehow stays in the search box. Try it out! 
When I click the options key to open the context menu the cursor shows up in the search box, so perhaps that's a bug. If this usage was never considered it would be nice to intergrate it :)

**Comment by foray1010** [comment]
Ah, yup, I will do it. Actually all of this function of arrow nav need to be implemented ourselves, I still figuring out how to do this one.
Because in Windows, we have a key that trigger contextmenu, but for OSX, it doesn't have, its option key is just the same as alt key in Windows. Do you have any suggestions how to implement it?

**Comment by MartinLichtblau** [comment]
Concerning the recognition of the OSX Alt-key (Which has the same functionality as the Win options-key) I found this: http://stackoverflow.com/questions/3902635/how-does-one-capture-a-macs-command-key-via-javascript

So it should work by recongnizing the keypress event for the options key (for Win) and the Options Key (for Mac which is the ALT key on Win) and trigger for both of them the contextmenu function. And it's not so bad when the alt key on windows would open the context menu as well.
P.S.: *I think I don't see the real problem here..*

**Comment by foray1010** [comment]
The function can easily be done. My question should be, how can user know when they press option key, it will trigger contextmenu?

For Windows, users know that there is an option key that can trigger contextmenu.
But for OSX, its option key doesn't behave the same way (I think), you cannot click `option` and trigger contextmenu in most of the application in OSX. Correct me if I am wrong

**Comment by MartinLichtblau** [comment]
Ahh, ok that's something I didn't know. I find the options key in windows really usefull though. 
It looks like the Options-key on Mac is used [to show additional information or functionality](http://www.macobserver.com/tmo/article/how-to-really-use-the-magical-option-key-on-the-mac) but it won't show the context menu when pressed, [such a key does not exist on OSX](http://apple.stackexchange.com/questions/32715/how-do-i-open-the-context-menu-from-a-mac-keyboard)!
So on OSX the most intuitive way to open the context menu would be the Options/Alt-key

**Comment by foray1010** [comment]
I don't think it is a good idea, because people just don't know/expect this feature when they click `option` key in OSX. Plus `option` key is actually `alt` key, may mess up other key combination.
So I suggest just drop it in OSX, as OSX users are used to it. Agree?

**Comment by MartinLichtblau** [comment]
Sounds good and logic! 
When they are not used to it they won't miss it :D

**Comment by foray1010** [comment]
![Challenge Accepted](http://vignette2.wikia.nocookie.net/animaljam/images/d/d2/Challenge-accepted.png)

**Comment by foray1010** [comment]
Sorry for late update, I was busy on rewriting the whole extension
This feature is completed, I hope I can release a new version before Feb 2017

```
Menu key => open menu in Windows/Linux
Control key => open menu in MacOS
```

I use Control key for MacOS because ctrl+left click means right click in mac

Related commits:
https://github.com/foray1010/Popup-my-Bookmarks/commit/be8a056dc1a9d59a8f7766225f32109843861553
https://github.com/foray1010/Popup-my-Bookmarks/commit/f91f26d971e65ccc0b8e2a538992e2431db03518
https://github.com/foray1010/Popup-my-Bookmarks/commit/9e62717a3fbe177860b926f5e0a51f839ed21896
https://github.com/foray1010/Popup-my-Bookmarks/commit/0a93424a140cd7e2855502911ec309b4f2dba315
